### PR TITLE
Add health checks for heap and file descriptor usage (by percent)

### PR DESCRIPTION
**Pull request by jordansissel**
This includes a pretty significant rewrite of the previous version of
this tool. My hope was to make it easier to allow easier maintenance
going forward -- be that new features or addition of testing.

### CODE REVIEW

**Comment by jordansissel** [comment]
[As promised](https://twitter.com/jordansissel/status/755888589255286785), here is a pretty big PR that I hope will be useful.

I confess I may have gone a bit overboard with the code changes, but my idea was to help make it easier to add new threshold conditions as Logstash's stats api grows and as we learn better rhow to monitor Logstash through this api.

I think my code needs a lot more comments, but the overall behavior seems to work well. Here's an example runs:

```
% ruby check_logstash.rb -H localhost
OK - Logstash looking healthy. | process.cpu.percent=0;;;0;100 mem.heap_used_percent=24;;;0;100 jvm.threads.count=18;;;0; events.in=1c;;;0; events.filtered=1c;;;0; events.out=1c;;;0;
OK: Heap usage at 24.00% (519153624 out of 2112618496 bytes in use)
OK: Open file descriptors at 1.07%. (44 out of 4096 file descriptors are open)


# -----
# When only 1 threshold value is given, it is used as the critical value:
% ruby check_logstash.rb -H localhost --heap-usage-threshold 10
CRITICAL - Logstash is unhealthy - CRITICAL: Heap usage at 25.00% (529418336 out of 2112618496 bytes in use) | process.cpu.percent=0;;;0;100 mem.heap_used_percent=25;;;0;100 jvm.threads.count=18;;;0; events.in=1c;;;0; events.filtered=1c;;;0; events.out=1c;;;0;
CRITICAL: Heap usage at 25.00% (529418336 out of 2112618496 bytes in use)
OK: Open file descriptors at 1.07%. (44 out of 4096 file descriptors are open)


#----
# Two thresholds can be given. The first is warn, and the second is critical.
% ruby check_logstash.rb -H localhost --heap-usage-threshold 10:80
WARNING - Logstash may not be healthy - WARNING: Heap usage at 25.00% (532450848 out of 2112618496 bytes in use) | process.cpu.percent=0;;;0;100 mem.heap_used_percent=25;;;0;100 jvm.threads.count=18;;;0; events.in=1c;;;0; events.filtered=1c;;;0; events.out=1c;;;0;
WARNING: Heap usage at 25.00% (532450848 out of 2112618496 bytes in use)
OK: Open file descriptors at 1.07%. (44 out of 4096 file descriptors are open)
```

**Comment by jordansissel** [comment]
This change also removes the cpu usage threshold from your version due to my belief that cpu usage is not an actionable measurement for logstash.

**Comment by jordansissel** [comment]
It has some limitations/bugs right now, for example, it exits 1 if Logstash is unreachable:

```
% ruby check_logstash.rb -H localhost --heap-usage-threshold 10:80
/home/jls/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "localhost" port 9600 (Errno::ECONNREFUSED)
```

**Comment by widhalmt** [comment]
This is... WOW. I'm speechless (and this doesn't happen very often to me). Thank you so much!

I'll definitely merge your pull request. It's just that I'm at a customers this week and I can't add the minor changes you mentioned to make it fully compatible to the monitoring plugin guidelines after the merge. But I do have some spare time next week and I'll look into it for sure.

I planned on improving the plugin slowly but this is just... WOW. Did I say that before? WOW.

**Comment by widhalmt** [comment]
Wow. The last weeks were just crazy. I'm happy I finally find the time to merge your pull request, finalise the Monitoring Plugin output and try to integrate this into the Icinga 2 template library / ITL so other users can use this plugin out of the box.

A short remark: I'm positive that I'll get some time from my employer to include all the changes needed to use the new API features when Logstash 5 is released.

**Comment by jordansissel** [comment]
Woohoo! :)

**Pull request merged**
